SYSTEM:
  ENV_PATH: "./env"
  TASK_DIR: "./tasks"
LLM:
  BASIC:
    model: "Qwen3-235B-A22B-agent"
    api_base: "https://quarkml.oa.fenqile.com/v1"
    custom_llm_provider: "openai"
    api_key: "lx-ai-1234"
    cache: true
    verbose: true
    streaming: false
    request_timeout: 60
    temperature: 0.2
    top_p: 0.2
    top_k: 10
    max_tokens: 20960
    max_retries: 2
  REASONING:
    model: "Qwen3-235B-A22B-agent"
    api_base: "https://quarkml.oa.fenqile.com/v1"
    custom_llm_provider: "openai"
    api_key: "lx-ai-1234"
    cache: true
    verbose: true
    streaming: false
    request_timeout: 60
    temperature: 0.2
    top_p: 0.2
    top_k: 10
    max_tokens: 20960
    max_retries: 2
  MYBASIC:
    model: "deepseek/deepseek-chat"
    cache: true
    verbose: true
    streaming: false
    request_timeout: 60
    temperature: 0.2
    top_p: 0.2
    top_k: 10
    max_retries: 2

PROMPT:
  DIR:  "./prompts"